name: NodeJS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        # Chỉ sử dụng Node.js 16.x và 18.x do giới hạn của GLIBC
        node-version: [16.x, 18.x]
      # Thêm fail-fast: false để tiếp tục chạy các phiên bản khác nếu một phiên bản thất bại
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: |
        npm ci || npm install
        
    - name: Build
      run: |
        npm run build --if-present
        
    - name: Test
      run: |
        npm test --if-present
